# Generated by Django 5.2.8 on 2025-12-07 22:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dormiu', models.DateTimeField(verbose_name='Data e Hora que deitou')),
                ('data_acordou', models.DateTimeField(verbose_name='Data e Hora que acordou')),
                ('total_horas_dormidas', models.FloatField(default=0.0, verbose_name='Total de Horas Dormidas (Calculado)')),
                ('qualidade_sono', models.IntegerField(choices=[(1, 'Ruim (Péssimo)'), (2, 'Abaixo da Média'), (3, 'Médio (Razoável)'), (4, 'Bom'), (5, 'Excelente (Revigorante)')], verbose_name='Avaliação da Qualidade do Sono')),
                ('notas_noite', models.TextField(blank=True, null=True, verbose_name='Notas e Observações da Noite')),
                ('exercicio_fisico', models.BooleanField(default=False, verbose_name='Exercício Físico Tarde')),
                ('alcool', models.BooleanField(default=False, verbose_name='Consumo de Álcool')),
                ('cafeina', models.BooleanField(default=False, verbose_name='Cafeína à Noite')),
                ('jantar_tarde', models.BooleanField(default=False, verbose_name='Jantar Tarde')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_sono', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Sono',
                'verbose_name_plural': 'Registros de Sono',
                'ordering': ['-data_dormiu'],
            },
        ),
    ]
