# Generated by Django 5.2.8 on 2025-11-30 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_dormiu', models.DateTimeField(verbose_name='Horário que foi dormir')),
                ('data_acordou', models.DateTimeField(verbose_name='Horário que acordou')),
                ('qualidade', models.CharField(choices=[('ruim', 'Ruim'), ('medio', 'Médio'), ('bom', 'Bom'), ('excelente', 'Excelente')], max_length=20, verbose_name='Qualidade do Sono')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Sono',
                'verbose_name_plural': 'Registros de Sono',
                'ordering': ['-data_dormiu'],
            },
        ),
    ]
