# Generated by Django 5.2.8 on 2025-12-07 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ajusta_coluna_qualidade'),
    ]   


    operations = [
        migrations.AlterField(
            model_name='registrosono',
            name='qualidade_sono',
            field=models.IntegerField(choices=[(1, 'Ruim (Péssimo)'), (2, 'Abaixo da Média'), (3, 'Médio (Razoável)'), (4, 'Bom'), (5, 'Excelente (Revigorante)')], verbose_name='Avaliação da Qualidade do Sono'),
        ),
    ]
