# Generated by Django 5.2.8 on 2025-12-07 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_registrosono_qualidade_sono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosono',
            name='alcool',
        ),
        migrations.RemoveField(
            model_name='registrosono',
            name='cafeina',
        ),
        migrations.RemoveField(
            model_name='registrosono',
            name='exercicio_fisico',
        ),
        migrations.RemoveField(
            model_name='registrosono',
            name='jantar_tarde',
        ),
        migrations.RemoveField(
            model_name='registrosono',
            name='notas_noite',
        ),
    ]
