# Generated by Django 6.0 on 2025-12-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_registrosono_alcool_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrosono",
            name="qualidade_sono",
            field=models.IntegerField(
                choices=[
                    (1, "Ruim (Péssimo)"),
                    (2, "Abaixo da Média"),
                    (3, "Médio (Razoável)"),
                    (4, "Bom"),
                    (5, "Excelente (Revigorante)"),
                ]
            ),
        ),
    ]
