# Generated by Django 6.0 on 2025-12-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_registrosono_qualidade_sono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrosono',
            name='qualidade_sono',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
