# Generated by Django 6.0 on 2025-12-08 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_registrosono_qualidade_sono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrosono',
            name='qualidade_sono',
        ),
    ]
